### ISSUE TITLE
Replace /dev/shm mount with --shm-size

### ISSUE THREAD

**Issue by zachhuff386** [arno01/steam#1]
Steam should run without mounting `/dev/shm` using `--shm-size 4g` which will be more secure. This will give the docker container a 4gb /dev/shm instead of the default 64mb which should prevent crashing from applications running out of shared memory.

This project also shows some other docker options and running applications in a Xephyr window for applications that don't need GPU. https://github.com/dockercask/dockercask

**Comment by arno01** [comment]
Such a great tip!
Much appreciated, thank you!

https://github.com/arno01/steam/commit/92a9d91a3f81fcef1b551a8814d7471ff9a18da8
