### ISSUE TITLE
new update to steam client makes it to throw this error

### ISSUE THREAD

**Issue by srihari-humbarwadi** [arno01/steam#23]
DISTRO : UBUNTU 16.04
You are missing the following 32-bit libraries and steam may not run:
libva-x11.so.1

I am on nvidia GTX 1060

**Comment by arno01** [comment]
Hi @srihari-humbarwadi , I have just pushed the new code that adds the ``libva-x11`` library.
The image will be soon uploaded to the Docker Hub.

Please try it and let me know if the issue still persists.
