### ISSUE TITLE
Instructions for use on Ubuntu 16.04 incomplete?

### ISSUE THREAD

**Issue by vgough** [arno01/steam#3]
docker-compose from Ubuntu 16.04 doesn't seem to like your compose file.   Can you document dependencies that you had to upgrade?

```bash
$ docker-compose run --rm steam --reset
ERROR: In file './docker-compose.yml' service 'version' doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.
```

```bash
$ docker-compose --version
docker-compose version 1.5.2, build unknown
```

**Comment by arno01** [comment]
Hello,

docker is getting developed so fast that distro vendors cannot follow it up.

basically, you need to use the latest docker-compose (or at least 1.7.x if I remember correctly):
you can obtain it from https://github.com/docker/compose/releases

I will update the doc.

Thanks!
