### ISSUE TITLE
Missing libjson-c3 dependency?

### ISSUE THREAD

**Issue by bagage** [arno01/steam#4]
Tried to run in today but it fails to start because of missing `libjsonc-3` dep.

Downloaded it from [debian stretch](http://ftp.de.debian.org/debian/pool/main/j/json-c/libjson-c3_0.12.1-1_i386.deb) and installed, Steam is now able to start.

**Comment by arno01** [comment]
@bagage what package does require libjsonc-3 exactly in your case?

please try running: `find /home/user/.local/ -type f -size -30M -exec ldd '{}' \; |grep libjson` inside your running Steam docker container `docker exec -ti steam bash`.  (It may take some time ...)

In my case only the libjsonc-2 showed up:
```
...
	libjson-c.so.2 => /lib/i386-linux-gnu/libjson-c.so.2 (0x...)
	libjson-c.so.2 => /lib/x86_64-linux-gnu/libjson-c.so.2 (0x...)
...
```

**Comment by bagage** [comment]
That's pulseaudio, coming from:

> export LD_PRELOAD="$LD_PRELOAD:$(find /h{1..20}_{32,64} -type f -name "*libpulsecommon*" -print0 2>/dev/null| tr '\0' ':')"

```
root@278d43613e74:~# find 2>/dev/null  /h{1..20}_{32,64} -type f -name "*libpulsecommon*" -exec ldd {} \; | grep libjson 
	libjson-c.so.3 => not found
	libjson-c.so.3 => not found
```

**Comment by arno01** [comment]
Ah, the external pulse dependency... :/ I am wondering if there there is a better way to handle this...
