### ISSUE TITLE
DNS requests flood

### ISSUE THREAD

**Issue by bagage** [arno01/steam#6]
When running steam within the container, I experimented very slow download bitrate. This is due to an upstream bug in steam for linux: https://github.com/ValveSoftware/steam-for-linux/issues/3401.
An easy workaround is to setup a DNS cache locally. I've done that in a custom branch (https://github.com/bagage/steam/tree/fix/dnsmasq) and it works great.

1. I installed `dnsmasq` directly within `steam` container and launch it with `docker run --dns=172.17.0.7 andrey01/steam`. You have to specify `--dns` argument due to docker limitation https://github.com/docker/docker/issues/541. If you do not provide the `--dns` argument, it will works as currently. If you are using `docker-compose`, it will work automatically due to `dns:` parameter in `docker-compose.yml`.
2. An alternative would be to add a dependency to a `dnsmasq` container via `docker-compose`, a single process per container. On the other hand this would prevent end-users from running steam via `docker run andrey01/steam`. They must use `docker-compose` and/or run `docker run someone/dnsmask` first and provide the proper `--dns` argument. But is this advised anyway?

What do you think?

**Comment by arno01** [comment]
Wow, very interesting find!

I am not in favor of the dependencies, so I vote for the DNS cache powered Steam container! (Since the overhead is minimal)

Please issue a PR so I can merge it. ;-)
