### ISSUE TITLE
Cannot open display

### ISSUE THREAD

**Issue by bagage** [arno01/steam#7]
Running `xhost +SI:localuser:$(id -un) && docker run andrey01/steam` is not enough to have graphical access from the container, at least on Wayland. 
I personally must use `docker run -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix andrey01/steam` as stated on some [SO posts](http://stackoverflow.com/questions/16296753/can-you-run-gui-apps-in-a-docker-container).

I think it would be worth mentioning on the README (as an fallback to `xhost +` maybe?).

**Comment by bagage** [comment]
Actually using `docker-compose`, both display and sound work as expected. I guess noone should use `docker run` directly.

**Comment by arno01** [comment]
@bagage if you want, you can always run it via a `docker run` command, just make sure you are not missing what is in `docker-compose.yml`.
